# Experiment 10: Create Dataset and Load Dataset

### Name: Lehalyaa L
### PRN: 25070123176
### Batch: ENTC - A2

In [4]:
# Dataset Creation

import pandas as pd

data = {
    "Roll_No": [101, 102, 103, 104, 105],
    "Gender": ["Female", "Male", "Female", "Male", "Female"],
    "Department": ["CSE", "ECE", "MECH", "CIVIL", "EEE"],
    "CGPA" : [7.98, 9.00, 7.01, 10.00, 8.3],
}

df = pd.DataFrame(data)

df.to_csv("student_data.csv", index=False) # Conversion of above file into csv
# Index is given as false to not include an additional column of index in the csv file

df

   Roll_No  Gender Department   CGPA
0      101  Female        CSE   7.98
1      102    Male        ECE   9.00
2      103  Female       MECH   7.01
3      104    Male      CIVIL  10.00
4      105  Female        EEE   8.30

In [5]:
df["a_year"] = ["2025- 2029", "2025- 2029", "2024- 2028", "2025- 2029", "2024- 2028"]
df.to_csv("student_data.csv", index=False)
df

   Roll_No  Gender Department   CGPA      a_year
0      101  Female        CSE   7.98  2025- 2029
1      102    Male        ECE   9.00  2025- 2029
2      103  Female       MECH   7.01  2024- 2028
3      104    Male      CIVIL  10.00  2025- 2029
4      105  Female        EEE   8.30  2024- 2028

In [6]:
df.shape

(5, 5)

In [7]:
df.size

25

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   a_year      5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [9]:
df.describe()

          Roll_No       CGPA
count    5.000000   5.000000
mean   103.000000   8.458000
std      1.581139   1.120455
min    101.000000   7.010000
25%    102.000000   7.980000
50%    103.000000   8.300000
75%    104.000000   9.000000
max    105.000000  10.000000

In [10]:
# Access Information of Department Column
df["Department"]

0      CSE
1      ECE
2     MECH
3    CIVIL
4      EEE
Name: Department, dtype: object

In [11]:
# Find out  Information  of Roll_No 103
df[df["Roll_No"] == 103]

   Roll_No  Gender Department  CGPA      a_year
2      103  Female       MECH  7.01  2024- 2028

In [12]:
# Find out datatype of each column

df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
a_year         object
dtype: object

In [13]:
# Perform mean, median, mode operation

mean1 = df["CGPA"].mean()
print("Average CGPA: ", mean1)

median = df["CGPA"].median()
print("Median CGPA: ", median)

mode =  df["CGPA"].mode()
print("Mode CGPA: ", mode)

Average CGPA:  8.458000000000002
Median CGPA:  8.3
Mode CGPA:  0     7.01
1     7.98
2     8.30
3     9.00
4    10.00
Name: CGPA, dtype: float64

In [14]:
# Insert a New Column Grade
df["Grade"] = ["B", "A", "B", "A+", "B+"]
df

   Roll_No  Gender Department   CGPA      a_year Grade
0      101  Female        CSE   7.98  2025- 2029     B
1      102    Male        ECE   9.00  2025- 2029     A
2      103  Female       MECH   7.01  2024- 2028     B
3      104    Male      CIVIL  10.00  2025- 2029    A+
4      105  Female        EEE   8.30  2024- 2028    B+

In [15]:
# delete Gender Column

df.drop("Gender", axis = 1, inplace = True)
df

   Roll_No Department   CGPA      a_year Grade
0      101        CSE   7.98  2025- 2029     B
1      102        ECE   9.00  2025- 2029     A
2      103       MECH   7.01  2024- 2028     B
3      104      CIVIL  10.00  2025- 2029    A+
4      105        EEE   8.30  2024- 2028    B+

In [16]:
# CGPA of topper
m =df[df["CGPA"] == df["CGPA"].max()]
m["CGPA"]

3    10.0
Name: CGPA, dtype: float64

In [17]:
# CGPA of PRN 105

n = df[df["Roll_No"] == 105]
print("PRN 105 CGPA: ", n["CGPA"])

PRN 105 CGPA:  4    8.3
Name: CGPA, dtype: float64

# Importing External Dataset

In [19]:
# Upload the Dataset

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [20]:
df.size

930

In [21]:
df.shape

(93, 10)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [23]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [24]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [25]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0