# Unit - 3 Data Wrangling

#### Experiment - 12: To Perform Preprocessing on a dataset and dealing with missing values

### Name: Lehalyaa L
### PRN: 25070123176
### Batch: ENTC A2

In [3]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'C1': [11,21, np.nan], 'C2':[15,np.nan, np.nan], 'C3' : [10,20,30]})

df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [6]:
df1.isna () # Boolean Function
#This gives True wherever the number or value is not there else it will give False

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [7]:
df1.notna () # Opposite of the above function

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [8]:
df1.isna().sum() # columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [9]:
df1.dropna () # NaN Rows are Dropped

     C1    C2  C3
0  11.0  15.0  10

In [11]:
df1.fillna(value = 'EDA')

     C1    C2  C3
0  11.0  15.0  10
1  21.0   EDA  20
2   EDA   EDA  30

In [12]:
df1.fillna (df1.mean()) # mean values of columns are calculated and that value is filled instead of NaN

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

## Data Preprocessing of Dataset - 1

In [36]:
data = {
    "Roll No" : [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "Name" : ["Akash", "Bejoy", "Christi", "Dev", "Emily", "Farhan", "Gautham", "Harini", "Iliz"],
    "Age" : [20, "-", 19, 20, 21, 20, "-", 18, "22"],
    "Marks" : ["90", 95, "-", 85, 65, "-", 89, 88, 98],
    "Department" : ["CSE", "ENTC", "CSE", "AIML", "RA", "ENTC", "entc", "CSE", "CSE"],
    "Admission Date" : ["22-09-2026", "01-08-2026", "05-08-2026", "22-09-2026", "01-08-2026", "05-08-2026", "26/09/2026", "22-09-2026", "01-08-2026"]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("Student_Data.csv", index = False)

In [37]:
df.replace("-", np.nan, inplace = True)
df

   Roll No     Name  Age Marks Department Admission Date
0        1    Akash   20    90        CSE     22-09-2026
1        2    Bejoy  NaN    95       ENTC     01-08-2026
2        3  Christi   19   NaN        CSE     05-08-2026
3        4      Dev   20    85       AIML     22-09-2026
4        5    Emily   21    65         RA     01-08-2026
5        6   Farhan   20   NaN       ENTC     05-08-2026
6        7  Gautham  NaN    89       entc     26/09/2026
7        8   Harini   18    88        CSE     22-09-2026
8        9     Iliz   22    98        CSE     01-08-2026

In [38]:
# Step 2: Convert columns to numeric where neeeded

df["Age"] = pd.to_numeric(df["Age"], errors = 'coerce')
df["Marks"] = pd.to_numeric(df["Marks"], 'coerce')
df

   Roll No     Name   Age  Marks Department Admission Date
0        1    Akash  20.0   90.0        CSE     22-09-2026
1        2    Bejoy   NaN   95.0       ENTC     01-08-2026
2        3  Christi  19.0    NaN        CSE     05-08-2026
3        4      Dev  20.0   85.0       AIML     22-09-2026
4        5    Emily  21.0   65.0         RA     01-08-2026
5        6   Farhan  20.0    NaN       ENTC     05-08-2026
6        7  Gautham   NaN   89.0       entc     26/09/2026
7        8   Harini  18.0   88.0        CSE     22-09-2026
8        9     Iliz  22.0   98.0        CSE     01-08-2026

In [39]:
# Step 3: Check Missing values

print("\n Missing Values:")
print(df.isnull().sum())

 Missing Values:
Roll No           0
Name              0
Age               2
Marks             2
Department        0
Admission Date    0
dtype: int64

In [40]:
# fill missing age with mean

df["Age"].fillna(df["Age"].mean(), inplace = True)
df

# Fill missing Marks with Median

'''for vareity data median  is used'''
df["Marks"].fillna(df["Marks"].median(), inplace = True)
df

/tmp/ipykernel_148/2253655059.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace = True)
/tmp/ipykernel_148/2253655059.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace = True)

   Roll No     Name   Age  Marks Department Admission Date
0        1    Akash  20.0   90.0        CSE     22-09-2026
1        2    Bejoy  20.0   95.0       ENTC     01-08-2026
2        3  Christi  19.0   89.0        CSE     05-08-2026
3        4      Dev  20.0   85.0       AIML     22-09-2026
4        5    Emily  21.0   65.0         RA     01-08-2026
5        6   Farhan  20.0   89.0       ENTC     05-08-2026
6        7  Gautham  20.0   89.0       entc     26/09/2026
7        8   Harini  18.0   88.0        CSE     22-09-2026
8        9     Iliz  22.0   98.0        CSE     01-08-2026

In [41]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission Date    0
dtype: int64

In [42]:
# Step 5: Fix Inconsistent Text Formatting

df["Department"] = df["Department"].str.upper()
df

   Roll No     Name   Age  Marks Department Admission Date
0        1    Akash  20.0   90.0        CSE     22-09-2026
1        2    Bejoy  20.0   95.0       ENTC     01-08-2026
2        3  Christi  19.0   89.0        CSE     05-08-2026
3        4      Dev  20.0   85.0       AIML     22-09-2026
4        5    Emily  21.0   65.0         RA     01-08-2026
5        6   Farhan  20.0   89.0       ENTC     05-08-2026
6        7  Gautham  20.0   89.0       ENTC     26/09/2026
7        8   Harini  18.0   88.0        CSE     22-09-2026
8        9     Iliz  22.0   98.0        CSE     01-08-2026

In [45]:
# Step 6: Convert Admission Data into standard Datetime Format

df["Admission Date"] = pd.to_datetime(df["Admission Date"], errors = 'coerce')
df

#If a value cannot be converted to a valid date then it will display
#NAT - Not a Time'''

   Roll No     Name   Age  Marks Department Admission Date
0        1    Akash  20.0   90.0        CSE     2026-09-22
1        2    Bejoy  20.0   95.0       ENTC     2026-08-01
2        3  Christi  19.0   89.0        CSE     2026-08-05
3        4      Dev  20.0   85.0       AIML     2026-09-22
4        5    Emily  21.0   65.0         RA     2026-08-01
5        6   Farhan  20.0   89.0       ENTC     2026-08-05
6        7  Gautham  20.0   89.0       ENTC            NaT
7        8   Harini  18.0   88.0        CSE     2026-09-22
8        9     Iliz  22.0   98.0        CSE     2026-08-01

In [47]:
# Step 7: Save Cleaned Datasheet

df.to_csv("cleaned_student_data.csv", index = False)

print("\n Cleaned CSV file is saved as cleaned_student_csv")

 Cleaned CSV file is saved as cleaned_student_csv

## Working with missing values in External Dataset

In [49]:
# Upload the Dataset

df2 = pd.read_csv("/content/Cars93.csv")
df

   Roll No     Name   Age  Marks Department Admission Date
0        1    Akash  20.0   90.0        CSE     2026-09-22
1        2    Bejoy  20.0   95.0       ENTC     2026-08-01
2        3  Christi  19.0   89.0        CSE     2026-08-05
3        4      Dev  20.0   85.0       AIML     2026-09-22
4        5    Emily  21.0   65.0         RA     2026-08-01
5        6   Farhan  20.0   89.0       ENTC     2026-08-05
6        7  Gautham  20.0   89.0       ENTC            NaT
7        8   Harini  18.0   88.0        CSE     2026-09-22
8        9     Iliz  22.0   98.0        CSE     2026-08-01

In [51]:
df2.isna().sum() # Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

## Inputing the Missing Value

In [57]:
df2['Luggage.room'] = df2['Luggage.room'].fillna(value = df2['Luggage.room'].mean())
df2

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [58]:
df2.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [61]:
# 2. Rear Seat room

df2["Rear.seat.room"] = df2["Rear.seat.room"].fillna(value = df2['Rear.seat.room'].mean())
df2

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [69]:
# 3. Airbags
df2["AirBags"] = df2["AirBags"].fillna(value = df2["AirBags"].mode().values[0])
df2

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [70]:
df2.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [71]:
# Save Cleaned Datasheet

df2.to_csv("updated_Cars93.csv", index = False)

print("\n Cleaned CSV file is saved as updated_Cars93.csv")

 Cleaned CSV file is saved as updated_Cars93.csv